heat_template_version: 2013-05-23

description: Simple template to deploy multiple compute instance

parameters:
  image:
    type: string
    description: Image ID or image name to use for the server
    constraints:
      - allowed_values: 
        - Debian Jessie 8.2
        - Ubuntu 14.04 LTS
        - CentOS 7.1
  flavor:
    type: string
    description: Sabor de la instancia
    default: m1.tiny
    constraints:
      - allowed_values: [m1.tiny,m1.small]
        description: InstanceType must be one of (m1.tiny m1.small)
  key_name:
    type: string
    default: clavecloud
    description: Clave SSH
  user_name:
    type: string
    label: jesus
    description: User name to be configured for the application
    constraints:
      - allowed_pattern: "[A-Z]+[a-zA-Z0-9]*"
        description: El usuario debe empezar con mayuscula
  db_name:
    type: string
    description: Drupal database name
    default: drupal
  db_username:
    type: string
    description: Admin account from database drupal
    default: drupal
    hidden: true
  db_password:
    type: string
    description: The drupal database admin account password
    default: drupal
    hidden: true
  db_root_password:
    type: string
    description: Root password for MySQL
    default: root
    hidden: true

resources:
  Instancia1:
    type: OS::Nova::Server
    properties:
      name: Debianapt
      key_name: {get_param: key_name}
      image: {get_param: image}
      flavor: {get_param: flavor}
      networks: [{"network":"red de jesus.bueno"}]
      user_data:
        str_replace:
          template: |
            #!/bin/bash -v
            export DEBIAN_FRONTEND=noninteractive
            apt-get update
            apt-get install -y mysql-server-5.5 apache2 drupal7
            mysqladmin -u root password db_rootpassword
            cat << EOF | mysql -u root --p=db_rootpassword
            CREATE DATABASE db_name;
            GRANT ALL PRIVILEGES ON db_name.* TO "db_user"@"localhost" IDENTIFIED BY "db_password";
            EXIT
            EOF
            ln -s /etc/drupal/7/apache2.conf /etc/apache2/conf.d/drupal7.conf
            a2enconf drupal7
            a2enmod rewrite
            sed -i 's/# RewriteBase/RewriteBase/g' /etc/drupal/7/htaccess
            sed -i 's/# RewriteBase/RewriteBase/g' /etc/drupal/7/htaccess
            service apache2 reload
          params:
            db_rootpassword: { get_param: db_root_password }
            db_name: { get_param: db_name }
            db_user: { get_param: db_username }
            db_password: { get_param: db_password }

  floating_ip:
     type: OS::Nova::FloatingIP
     properties:
       pool: ext-net

  association:
     type: OS::Nova::FloatingIPAssociation
     properties:
       floating_ip: { get_resource: floating_ip }
       server_id: { get_resource: Instancia1 }