heat_template_version: 2013-05-23

description: Simple template to deploy multiple compute instance

parameters:
  image:
    type: string
    description: Image ID or image name to use for the server
    constraints:
      - allowed_values: 
        - Debian Jessie 8.2
        - Ubuntu 14.04 LTS
        - CentOS 7.1
  flavor:
    type: string
    description: Sabor de la instancia
    default: m1.tiny
    constraints:
      - allowed_values: [m1.tiny,m1.small]
        description: InstanceType must be one of (m1.tiny m1.small)
  key_name:
    type: string
    default: clavecloud
    description: Clave SSH
  user_name:
    type: string
    label: jesus
    description: User name to be configured for the application
    constraints:
      - allowed_pattern: "[A-Z]+[a-zA-Z0-9]*"
        description: El usuario debe empezar con mayuscula
  db_name:
    type: string
    description: Drupal database name
    default: drupal
  db_username:
    type: string
    description: Admin account from database drupal
    default: drupal
    hidden: true
  db_password:
    type: string
    description: The drupal database admin account password
    default: drupal
    hidden: true
  db_root_password:
    type: string
    description: Root password for MySQL
    default: root
    hidden: true

resources:
  Instancia1:
    type: OS::Nova::Server
    properties:
      name: Drupal_db
      key_name: {get_param: key_name}
      image: {get_param: image}
      flavor: {get_param: flavor}
      networks: [{"network":"red de jesus.bueno"}]
      admin_user: {get_param: user_name}
      user_data:
        str_replace:
          template: |
            #!/bin/bash -v
            yum install -y mariadb mariadb-server
            
            systemctl start mariadb.service
            systemctl enable mariadb.service
            
            mysqladmin -u root password db_rootpassword
            
            cat << EOF | mysql -u root --password=db_rootpassword
            CREATE DATABASE db_name;
            GRANT ALL PRIVILEGES ON db_name.* TO "db_user"@"%"
            IDENTIFIED BY "db_password";
            FLUSH PRIVILEGES;
            EXIT
            EOF
          
          params:
            db_rootpassword: { get_param: db_root_password }
            db_name: { get_param: db_name }
            db_user: { get_param: db_username }
            db_password: { get_param: db_password }

  Instancia2:
    type: OS::Nova::Server
    properties:
      name: Drupal_wb
      key_name: {get_param: key_name}
      image: {get_param: image}
      flavor: {get_param: flavor}
      networks: [{"network":"red de jesus.bueno"}]
      admin_user: {get_param: user_name}
      user_data:
        str_replace:
          template: |
            #!/bin/bash -v
            yum install -y httpd wget unzip
            yum install -y php php-mbstring php-gd php-xml php-pear 
            
            wget http://ftp.drupal.org/files/projects/drupal-7.33.zip
            unzip -q drupal-7.33.zip -d /var/www/html/
            
            mv /var/www/html/drupal-7.33/ /var/www/html/drupal
            chown -R apache:apache /var/www/html/drupal
            cd /var/www/html/drupal/sites/default/
            
            chcon -R -t httpd_sys_content_rw_t /var/www/html/drupal/sites/
            
            sed -i 's/databasename/db_name/g' /var/www/html/drupal/sites/default/default.settings.php
            sed -i 's/username/db_user/g' /var/www/html/drupal/sites/default/default.settings.php
            sed -i 's/password/db_password/g' /var/www/html/drupal/sites/default/default.settings.php
            sed -i 's/localhost/db_host/g' /var/www/html/drupal/sites/default/default.settings.php 
            sed -i 's/myprefix_/drupal_/g' /var/www/html/drupal/sites/default/default.settings.php 
          
            cp /var/www/html/drupal/sites/default/default.settings.php /var/www/html/drupal/sites/default/settings.php
            
            setenforce 0
            systemctl start httpd.service
            systemctl enable httpd.service
          
          params:
            db_name: { get_param: db_name }
            db_user: { get_param: db_username }
            db_password: { get_param: db_password }
            db_host: { get_attr: [Instancia1, networks, "red de jesus.bueno", 0] }

  floating_ip:
     type: OS::Nova::FloatingIP
     properties:
       pool: ext-net

  floating_ip2:
     type: OS::Nova::FloatingIP
     properties:
       pool: ext-net

  association:
     type: OS::Nova::FloatingIPAssociation
     properties:
       floating_ip: { get_resource: floating_ip }
       server_id: { get_resource: Instancia1 }

  association2:
     type: OS::Nova::FloatingIPAssociation
     properties:
       floating_ip: { get_resource: floating_ip2 }
       server_id: { get_resource: Instancia2 }